Repository techfellows/website, pull requests merged in 2020-10, with the labels that each got.

#5 Update Docusaurus config.
  docusaurus.config.js
  static/img/techfellows.jpg
Labels: hacktoberfest

#6 Add Travis CI pipeline
  .travis.yml
Labels: hacktoberfest, hacktoberfest-accepted

#7 Create the first blog post
  blog/2019-05-28-hola.md
  blog/2019-05-29-hello-world.md
  blog/2019-05-30-welcome.md
  blog/2020-10-03-tech-fellows-intro.md
Labels: hacktoberfest, hacktoberfest-accepted

#8 Update content for new comers
  README.md
  src/pages/about.js
Labels: hacktoberfest

#10 fix: baseUrl for deployment to github pages
  docusaurus.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#12 Add a custom domain
  docusaurus.config.js
  static/CNAME
Labels: hacktoberfest

#19 convert techfellows image to svg
  docusaurus.config.js
  static/img/techfellows.svg
Labels: hacktoberfest-accepted

#21 Add tutorials section.
  docs/doc1.md
  docs/doc4.md
  docs/doc5.md
  docs/doc6.md
  docs/doc7.md
  docs/doc8.md
  docusaurus.config.js
  sidebars.js
  static/img/Daniel.jfif
  static/img/Mohammed.jfif
Labels: hacktoberfest

#25 changed mobile view on about page to grids of rows
  package-lock.json
  src/css/custom.css
  src/pages/about.js
Labels: hacktoberfest-accepted
